# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-06 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(help_text='Keep it under 100 characters', max_length=100, unique=True)),
                ('password', models.CharField(help_text='Keep it under 100 characters', max_length=100)),
            ],
        ),
    ]
