# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-06 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='t1',
            field=models.BooleanField(default=False, verbose_name='Animal Cruelty'),
        ),
        migrations.AddField(
            model_name='profiles',
            name='t2',
            field=models.BooleanField(default=False, verbose_name='It was all a dream'),
        ),
        migrations.AddField(
            model_name='profiles',
            name='t3',
            field=models.BooleanField(default=False, verbose_name='He/She was dead all along'),
        ),
        migrations.AddField(
            model_name='profiles',
            name='t4',
            field=models.BooleanField(default=False, verbose_name='Main character dies'),
        ),
        migrations.AddField(
            model_name='profiles',
            name='t5',
            field=models.BooleanField(default=False, verbose_name='Cliff Hanger Ending'),
        ),
        migrations.AddField(
            model_name='profiles',
            name='t6',
            field=models.BooleanField(default=False, verbose_name='Cliff Hanger Ending without sequel'),
        ),
    ]
