# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-06 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170506_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='t7',
            field=models.BooleanField(default=False, verbose_name=b'Suicide'),
        ),
    ]
