# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-10 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profiles_t7'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiles',
            name='id',
        ),
        migrations.AlterField(
            model_name='profiles',
            name='userid',
            field=models.CharField(help_text='Keep it under 100 characters', max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
