# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-07 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Keep it under 100 characters, using a release date if needed', max_length=100, unique=True)),
                ('t1', models.BooleanField(default=False, verbose_name=b'Animal Cruelty')),
                ('t2', models.BooleanField(default=False, verbose_name=b'It was all a dream')),
                ('t3', models.BooleanField(default=False, verbose_name=b'He/She was dead all along')),
                ('t4', models.BooleanField(default=False, verbose_name=b'Main character dies')),
                ('t5', models.BooleanField(default=False, verbose_name=b'Cliff Hanger Ending')),
                ('t6', models.BooleanField(default=False, verbose_name=b'Cliff Hanger Ending without sequel')),
                ('t7', models.BooleanField(default=False, verbose_name=b'Suicide')),
            ],
        ),
    ]
