# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-11 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='id',
        ),
        migrations.AlterField(
            model_name='movies',
            name='title',
            field=models.CharField(help_text='Keep it under 100 characters, using a release date if needed', max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
